name = "Mechanical SMP"
author = "SzyZu"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cf05bd93a2e53a5259cf92484e76fd34dba282dd2030fccc61c724c68dfd594"

[versions]
fabric = "0.15.7"
minecraft = "1.18.2"
