name = "Mechanical SMP"
author = "SzyZu"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb9ed8bbd1aab3dcb859f4d2d91a94521c7497fbf9c4b88bb588b25d6fcd2623"

[versions]
fabric = "0.15.7"
minecraft = "1.18.2"
